using FluentValidation;
using TravelAccomodationAPI.ModelClass.RequestModel;

namespace TravelAccomodationAPI.Validators.HotelMasterValidators
{
    public class AddHotelFilesRequestValidator : AbstractValidator<AddHotelFilesRequest>
    {


        private readonly string[] _allowedExtensions =
           {
        ".jpg", ".jpeg", ".png", ".pdf"
    };

        private const long MaxFileSize = 5 * 1024 * 1024; // 5 MB

        public AddHotelFilesRequestValidator()
        {
            RuleFor(x => x.HotelId)
                .GreaterThan(0)
                .WithMessage("HotelId must be greater than zero.");

            RuleFor(x => x.FIle)
                .NotNull()
                .WithMessage("File is required.")
                .Must(BeValidFile)
                .WithMessage("Invalid file.");

            RuleFor(x => x.FIle)
                .Must(BeValidSize)
                .WithMessage("File size must not exceed 5 MB.");

            RuleFor(x => x.FIle)
                .Must(HaveValidExtension)
                .WithMessage("Only JPG, JPEG, PNG, or PDF files are allowed.");

            RuleFor(x => x.FileName)
                .MaximumLength(50)
                .When(x => !string.IsNullOrWhiteSpace(x.FileName))
                .WithMessage("FileName must not exceed 50 characters.");

            RuleFor(x => x.Description)
                .MaximumLength(500)
                .WithMessage("Description must not exceed 500 characters.");

            //RuleFor(x => x.FileId)
            //    .Equal(0)
            //    .WithMessage("FileId must not be supplied. It is generated by the system.");
        }

        private bool BeValidFile(IFormFile file)
        {
            return file != null && file.Length > 0;
        }

        private bool BeValidSize(IFormFile file)
        {
            return file != null && file.Length <= MaxFileSize;
        }

        private bool HaveValidExtension(IFormFile file)
        {
            if (file == null) return false;

            var extension = Path.GetExtension(file.FileName);
            return _allowedExtensions.Contains(extension.ToLower());
        }


    }
}
